### ISSUE TITLE
Markdown Viewer stops working in version 1.8.1 in Firefox 114.0.1

### ISSUE THREAD

**Issue by robertpba** [KeithLRobertson/markdown-viewer#104]
Markdown Viewer was automatically updated yesterday (2023-06-12) to version 1.8.1 and now rendering does not work anymore. Instead, Firefox prompts me to choose what to do with the Markdown file, offering to save it. I'm using Firefox 114.0.1 (64-bit) on Linux.

**Comment by Cimbali** [comment]
This is a known issue that happens to all markdown viewer versions. It's likely this happened more due to a Firefox update. Did you maybe change for a snap install?

The usual mitigation techniques are listed in the README (except option 1 doesn't apply to v1.8, only to v2 which is currently under review) 

https://github.com/Cimbali/markdown-viewer#support-for-local-files-on-linux-and-macos

**Comment by robertpba** [comment]
You are right! Somehow my apt install of firefox was replaced by the snap release without me noticing, perhaps as part of an upgrade. Purged the snap release and re-installed the apt package from the mozillateam ppa. Now Markdown Viewer can display local .md files again.
