### ISSUE TITLE
Doesn't work in 58.0b4 (64-bit) Ubuntu 16.04

### ISSUE THREAD

**Issue by noelniles** [KeithLRobertson/markdown-viewer#17]
I upgraded to Quantum and it seems this is broken. Any ideas?

**Comment by KeithLRobertson** [comment]
Can't say for sure without more information than "this is broken". Perhaps you're referring to what was reported in issue #8. I and others have noticed that markdown is not converted for remote (http/s:) URLs but still works for local (file:) documents. Is that what you're seeing?

As noted there, this is a change since FF 56+. The viewer activates, but FF now won't execute scripts in the page. Seems to be a change in permissions but I haven't seen any documentation on what changes to be made to the add-on.

If you can provide more details to show this as different issue, I'll reopen this. For now I'm close as a duplicate.
