### ISSUE TITLE
Non-ASCII characters display incorrectly in UTF-8 encoded file

### ISSUE THREAD

**Issue by jledruide** [KeithLRobertson/markdown-viewer#3]
Hi,

when I read an MD file with markdown-viewer, some characters don’t display the right code.

For example (in French):

    Utiliser un logiciel d'Ã©change (Dropbox ?) 

My MD files are under UTF-8 format and if I’m testing to convert the file in ANSI format, it works. And if I convert your test-file.md, I have the same issue.

Did you reproduce this problem?

**Comment by KeithLRobertson** [comment]
Does your .md document start with a UTF-8 Byte Order Marker (EF BB BF)? It **must** for the reader to know how it's encoded. Be sure to save your Markdown documents as "UTF-8 with BOM". test-file.md comes from Git in this encoding, so the extension should display the Unicode characters as-is if you don't convert the file.

ANSI just means your file is using the default code page encoding for your machine. Probably the reader uses this encoding by default when there's no BOM, which is why it works when converted to ANSI on your machine.

**Comment by jledruide** [comment]
Yes, it’s in UTF-8 without BOM, like all my other files. I used to do this for my PHP documents for example.

Now, I need to check in my other computer, I wonder if I don’t create these files under Linux which is in UTF-8 by default (with or without BOM ?).

So, thanks for this explanation, I understand now.

**Comment by jledruide** [comment]
And I confirm that Atom create his file without BOM (under Windows).
There is an issue about that : [Support for Unicode encodings with BOM](https://github.com/atom/encoding-selector/issues/18).

Never easy

**Comment by KeithLRobertson** [comment]
Thiht's Markdown Viewer (from which this one is derived) using FF's older plugin API had some code which would *force* the file to be read as UTF-8. With that, the file didn't need a BOM, *but* (although I didn't test it) I think that would mess things up if your file **isn't** UTF-8!

However, the Web Extensions API is more restrictive, and so doing the same thing wasn't possible, or at least I couldn't make it happen. Not sure I would even want to, though, since it would make the plugin support **only** UTF-8.

In the end...   Yeah man, there's gotta be a BOM. Sorry. :-) Plenty of other editors support saving UTF-8 with BOM.

**Comment by tukoz** [comment]
For vim users see [How to add a BOM with vim](https://superuser.com/questions/696361/how-to-get-the-markdown-viewer-addon-of-firefox-to-work-on-linux/1175837)

**Comment by nltesown** [comment]
Couldn't there be an option that allows to choose the default : 1) current setting or 2) always UTF-8 (even BOM-less)? The current situation isn't satisfactory because you don't always choose how the file you want to display was encoded.
