### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by gaul** [KeithLRobertson/markdown-viewer#34]
Which character encoding does Markdown View use?  I see `✓` rendered as `âœ“`.

**Comment by y6nH** [comment]
The generated HTML document does not specify an encoding for UTF-8 files without a byte order mark. If you have control of the file you're viewing, make sure you save it as UTF-8 with a BOM. Otherwise, you can find the character encoding options hidden deep in the browser menu and set it there.

It would be nice to have the generated HTML default to UTF-8.

**Comment by Keith94** [comment]
Also with [this .md file](https://raw.githubusercontent.com/bengarrett/RetroTxt/master/README.md), it renders `·` like `Â·`

**Comment by KeithLRobertson** [comment]
> It would be nice to have the generated HTML default to UTF-8

UTF-8 is a mapping from characters to/from bytes. Character encoding is only relevant when you're working with byte streams, for example when covering the .md file (a byte stream) into a markdown character stream. The extension takes the markdown character stream and converts it into an HTML character stream (using markdown-it), and displays that in the browser. It never handles HTML as a byte stream. Therefore, character encoding is not relevant when we're talking about the generated HTML.

> I see ✓ rendered as âœ“.
> renders · like Â·

As noted in several other issues, this extension requires a BOM on the markdown file so that it can determine the character encoding. If you can determine how to make it default to UTF-8, I would welcome the PR submission.
