### ISSUE TITLE
Some non ASCII characters are not displayed correctly (Encoding Bug?)

### ISSUE THREAD

**Issue by TWT-GSCHW** [KeithLRobertson/markdown-viewer#4]
Hello again, I sometimes have markdown files written in German which tend to use umlauts like ä, ö, ü, ß. None of those are displayed correctly. The markdown file is saved as UTF-8 so it should be correct in the original file, but in the HTML representation it shows up like Ã¼ for an ü and Ã¤ for an ä and so on. Maybe the converter needs to recognize special characters like those or it could also be sufficient to add `<meta charset="UTF-8">` to the HTML-header?
Greetings

**Comment by KeithLRobertson** [comment]
A file is a sequence of bytes, but Markdown is a sequence of characters. When the extension reads the file, it has to know how to convert bytes into characters, called an encoding. You have to know the encoding early, ideally before reading the file, before you can read any characters from it. So embedding a charset="UTF-8" is already too late; there is already an encoding in place in order to interpret those **characters**.

By default, Firefox uses the default encoding for your machine which is a code page. As I understand it, a code page maps single bytes to single characters, but UTF-8 isn't and cannot be a code page because it has variable number of bytes representing a character. If you can find some way to tell Firefox to read a file as UTF-8 by default, please publish it, but I haven't found it.

An alternative is that a file can start with a Byte Order Marker (BOM), a sequence of bytes that specifies the encoding for the file. If your Markdown file was saved as "UTF-8 with BOM", then when viewed in Firefox, it will switch to that encoding when presenting the file to the Markdown Viewer extension.

**Comment by KeithLRobertson** [comment]
Oh I think I see what you mean; you suggest adding the meta element to the HTML output. I don't think that will help. The Markdown file is converted from bytes to characters to get the Markdown text content; the plugin converts Markdown text to HTML text -- characters all the way -- so encoding is not a problem, and German characters in Markdown will still be German characters in the HTML.

If you view are viewing Markdown in UTF-8 with BOM, I don't know why the German characters are not viewing for you. I can see German, Russian, etc. characters in the styled document just fine.

Can you provide more information? Your Markdown input is UTF-8 **with BOM**, right?

**Comment by TWT-GSCHW** [comment]
Ah! Ok that was it. The document was saved as UTF-8 without BOM. When adding the BOM it works perfectly fine. Thank you!

> By default, Firefox uses the default encoding for your machine which is a code page.

I am a bit puzzled though, because my system language is en_DK.UTF-8 so Firefox should be able to guess that the file is in UTF-8 format. But I found various questions regarding the inability to set the default encoding in Firefox via Google. I also found multiple bug reports for this problem like [this one](https://bugzilla.mozilla.org/show_bug.cgi?id=158285).

But for me, the problem is solved. Thank you very much KeithLRobertson!
