### ISSUE TITLE
Extension Conflict?

### ISSUE THREAD

**Issue by amreus** [KeithLRobertson/markdown-viewer#41]
I'll refer you to [this issue](https://github.com/buggyj/savetiddlers/issues/40).

In short, `markdown-viewer` does not work with the `save-tiddlers` extension enables.

Thanks.

**Comment by KeithLRobertson** [comment]
Here's what's going on:

It's certainly possible for you to open a .md URL in the browser which is already styled; md from github comes pre-styled all the time. (E.g. https://github.com/KeithLRobertson/markdown-viewer/blob/master/README.md) We don't want to style it again. And we shouldn't because we don't have the raw original markdown text. To avoid re-styling, markdown-viewer looks at the document body for a single PRE element; its textContent is the original markdown. If it doesn't find exactly that, MV assumes the document is already styled and doesn't activate.

Save-tiddlers adds an additional element into the body, a DIV with id #tiddlyfox-message-box. This is throwing off markdown-viewer's detection of unstyled text. Now the body has two elements, where only one was expected.

I would argue therefore the fault lies mostly with save-tiddlers. By adding an element to the body, it is in effect styling the text. I could change MV to just look for the first element being PRE, but that doesn't seem right. Certainly a server-side .md renderer could produce output that happens to start with a PRE element.

Suggestions anyone? @Cimbali, any thoughts here?

**Comment by Cimbali** [comment]
I think the assumption of a single `<pre>` meaning unmodified text content is good.

I'm not sure what savetiddlers does, I'm quite confused by it. It says it is a download tool for a kind of wikis, in which case I don't know why it needs to modify pages that are not part of those wikis. Or are there markdown pages as part of those wikis?

**Comment by KeithLRobertson** [comment]
Cimbali and I agree that this plugin's approach to detecting unstyled Markdown makes sense, and that the savetiddlers extension is doing something unreasonable that throws off that detection. Therefore, we would argue savetiddlers is the one which should be fixed. Closing this issue.
