### ISSUE TITLE
Display table of contents

### ISSUE THREAD

**Issue by gaul** [KeithLRobertson/markdown-viewer#42]
I have several large markdown files where a table of contents would help navigate.  Can this addon optionally allow this, perhaps via some directive in the markdown file?

**Comment by Cimbali** [comment]
Probably more a rendering feature than a document feature, I think. Otherwise we need to extend the markdown syntax somehow, and there's probably already enough of that going around.

I've created a version that does not have any styling because I think some thought should go into that. Typically thinking of responsive designs, but also whether the toc should be fixed or floating etc. The good thing is that with the custom CSS you can always override it. It could be dropdown, removable, etc. all just with css.

For example, if you try the code from PR #47 and put this in your custom CSS preferences:

	#__markdown-viewer-toc__ {
	  float: right;
	  background: lightgrey;
	  padding: .5em 1em;
	  border-radius: .5em;
	  max-width: 20%;
	}

	#__markdown-viewer-toc__::before {
	  content: "Table of Contents";
	  text-align: center;
	  display: block;
	  font-weight: bold;
	  text-decoration: underline;
	  margin-bottom: .5em;
	}

	#__markdown-viewer-toc__ * {
	  white-space: nowrap;
	  overflow: hidden;
	  text-overflow: ellipsis;
	}

	#__markdown-viewer-toc__ a {
	  color: black;
	}

	#__markdown-viewer-toc__ ul {
	  list-style: inside "• ";
	  padding: 0;
	  margin: 0;
	}

	#__markdown-viewer-toc__ ul ul {
	  padding-left: 1.5em;
	}

Then you get this ugly-ass yet proof-of-concept thing:

![markdown viewer readme with a toc](https://screenshotscdn.firefoxusercontent.com/images/642d765b-dff3-4a5c-85bf-783b3a6a606c.png)

**Comment by KeithLRobertson** [comment]
I don't think that's ugly-ass! Really very cool feature!
As noted elsewhere, the only thing I think this needs is the ability for the user to toggle it on and off.
