### ISSUE TITLE
Cannot render <html> <head> <title> content

### ISSUE THREAD

**Issue by bouygues** [KeithLRobertson/markdown-viewer#64]
When "<head> <head> <title> " appears in content of a Markdown file, it will not be renderred correctly -- cannot display at all. 
Sample as following: 
```
# Title: my tile
## Sub title: my sub title
    This is the content, which includes <html><head><title> tags.
    But you cannot see me here. Cause the extension cannot render any content after <html> tag in previous line.  
<br>
- This is the content, which includes <html><head><title> tags.
- But you cannot see me here. Cause the extension cannot render any content after <html> tag in previous line.    
```

**Comment by bouygues** [comment]
Provide the content here again.

# Title: my tile
## Sub title: my sub title
    This is the content, which includes <html><head><title> tags.
    But you cannot see me here. Cause the extension cannot render any content after <html> tag in previous line.  
<br>
- This is the content, which includes <html><head><title> tags.
- But you cannot see me here. Cause the extension cannot render any content after <html> tag in previous line.

**Comment by bouygues** [comment]
OMG, I cannot type the markdown sample code here. 
So I attach it as a txt file. 
[test.md.txt](https://github.com/KeithLRobertson/markdown-viewer/files/3899778/test.md.txt)

**Comment by Cimbali** [comment]
Since html tags are allowed in markdown, if you want tags that appear in the text they should be escaped in the source. 

Does using  either `\<html\>` or `&lt;html&gt;` work?

**Comment by Cimbali** [comment]
So I had a quick look at this:
- Using `\<html\>\<head\>\<title\>` seems to work.
- The `<head>` tag is left as-is in the markdown output, I suppose firefox interprets it generously (that is, ignoring the missing `/`) as the end of the document, which is why the page is cut off at that level

So this is basically a case of invalid input (so I wouldn’t call this a bug). If we want to handle this more gracefully, we could use the [markdown-it-sanitizer plugin](https://github.com/svbergerem/markdown-it-sanitizer), that should be more or less plug-and-play.
