### ISSUE TITLE
Does not work on Firefox 88.0 / Windows

### ISSUE THREAD

**Issue by kgraefe** [KeithLRobertson/markdown-viewer#79]
When loading a local Markdown file the file is not rendered at all.  [GitLabMarkdownViewer](https://github.com/painyeph/GitLabMarkdownViewer) does work but it lacks some features I'd like to have.

In the Windows Registry I had to set `Computer\HKEY_CLASSES_ROOT\.md\Content Type` to `text/html`. Otherwise Firefox always presents the download dialog.

TBH I don't know where to start digging, so that is all the information I have. :-/

**Comment by kgraefe** [comment]
Setting `Computer\HKEY_CLASSES_ROOT\.md\Content Type` to `text/plain` still omits the download dialog. Still no rendering, though.

**Comment by Cimbali** [comment]
Just tested, works for me with Firefox 88 on Windows 10. I have no `.md` key in my registry.

**Comment by Cimbali** [comment]
- When you get an non-rendered page, but no download dialog, can you try reloading the page via the address bar (and not via F5 or the refresh button) ?

- Can you also report the actual file name (full path) ?

The mime type should not matter by the way, as we only match the file name. It does get in the way when firefox thinks it should not open some file because of a wrong or unexpected mime type, but it’s not what we use to find which files to open.

**Comment by kgraefe** [comment]
Thank you! I deleted it and it works now.

**Comment by Cimbali** [comment]
Great ! :)
