### ISSUE TITLE
Web link from local file not working

### ISSUE THREAD

**Issue by SUonGH** [KeithLRobertson/markdown-viewer#87]
For example, in rendering markdown from a local file, the link generated by `[the BBC](www.bbc.com/news)` will try to access something like `file:///C:/Users/path/to/file/directory/www.bbc.com/news` instead of `www.bbc.com/news`.

**Comment by Cimbali** [comment]
That’s how all links work: if you’re changing the protocol, you should add it to the link. Otherwise it just uses the same protocol. In particular, this means:

- from a `https://` website, if you want to point to a local file, you should add `file://` in front of `/C:/Users/....`
- from a `file://` page, if you want to point to a website, you should add `https://` in front of `www.bbc.com/news`

`[the BBC](https://www.bbc.com/news)` will work fine.
