### ISSUE TITLE
Large font size when printing the HTML view into PDF

### ISSUE THREAD

**Issue by nomadbyte** [KeithLRobertson/markdown-viewer#89]
The Markdown properly renders into HTML and is displayed according to browser's Font setting (tested with Firefox 94.0 under Ubuntu Linux). However, when trying to print the rendered page into a PDF (Save as PDF), the Preview and the resulting document appear in larger font (e.g. body text: 12pt, H1:27pt, quite liberal spacing too).  Changing the Font setting in the browser does not appear to have any direct effect on the printed font sizes.

The plugin is very useful in reading/browsing project docs. It'd be nice to have its **print view** defaults better optimized so it'd appear more scaled and balanced for paper medium.

**Comment by Cimbali** [comment]
The browser font setting seems unrelated on other websites too.
- Can’t you just change the scale option of the preview window to e.g. 50%?
- What would be a good default font size for print views? 12pt seems fine in an office document but it might not be interpreted the same way maybe?
  You can experiment with css in your add-on options by wrapping in a media query, e.g.
  ```css
  @media print {
    body { font-size: 8pt !important; }
  }
  ```

**Comment by Cimbali** [comment]
I think I’ve arrived to something better out-of-the-box, with smaller fonts and less spacing. The print view is also not affected by the selected style anymore (github or default), and scaling of images has also been fixed to some degree (they can’t be wider than the page anymore). 2 additional details are that we should have more sensible page breaks now (e.g. not after titles), and that the `link text (url)` display now always shows the ` (url)` part in the base font size, which makes it less absurd when titles with bigger fonts have links in them. Line spacing is still 1.5 because I find 1 to be really unreadable.

Here’s [a PDF-printed README example](https://github.com/KeithLRobertson/markdown-viewer/files/7661767/What.is.Pympress.pdf) from another project, [pympress](https://github.com/Cimbali/pympress/blob/master/README.md). here’s a side-by-side screenshot of our PDF conversion (right) and okular’s native markdown rendering (left):

![image](https://user-images.githubusercontent.com/6126377/144874766-8cbb60a5-8cfc-46b6-aee6-8857d20d23ae.png)

You can see there’s a number of things we do better, including images, displaying URLs, better list detection, and wrapping/styling code elements. The only margins you see on the page are from the printing dialog. (The difference in background colors is not part of the differences and only marks the active window.)

Any feedback is welcome as I’m not sure I can think of all use cases out of the box (printing to PDF is not a feature I use much), and styling always remains a little subjective. For example, I think there is a case for reintroducing some padding after a paragraph to make things clearer.

If you want to test it (@nomadbyte or anyone else, maybe  @KeithLRobertson has an opinion?), you can:
1. download the [current master as zip](https://github.com/KeithLRobertson/markdown-viewer/archive/refs/heads/master.zip) and extract it somewhere
2. go to the `about:debugging#/runtime/this-firefox` page of your Firefox, which you can also navigate to via the
“Manage your extensions” page (`about:addons`)  > Menu (Gear icon) > Debug add-ons.
3. Click the “Load temporary Add-on…” button and select the `manifest.json` file in the directory where you extracted the zip in step 1

**Comment by Cimbali** [comment]
Closing this and releasing as there is no further feedback. I’ll release a new version on AMO, any small adjustments can be done with `@media print { … }` queries in CSS customisation.
