### ISSUE TITLE
Doesn't work on Ubutnu 18.04

### ISSUE THREAD

**Issue by erezinman** [KeithLRobertson/markdown-viewer#90]
Hi, 
I can't get the plugin to work. I tried two cases:
1. Going to your [README.md](https://raw.githubusercontent.com/KeithLRobertson/markdown-viewer/master/README.md) file in raw mode doesn't render it using the plugin (shows plain text).
2. Using a path to a local file (located in either`~` or in `~/Downloads`) just calls opens a download dialog window.

Thanks

**Comment by Cimbali** [comment]
Hi @erezinman, I’m afraid you’ve fallen in some pitfalls that are, alas, out of our control.

1. On github, there are security headers, specifically `content-security-policy: default-src 'none'; style-src 'unsafe-inline'; sandbox` that prevent extensions from modifying the page (so markdown-viewer can’t render anything).  You can try a random raw makdown page on gitlab instead:   https://gitlab.com/gnachman/iterm2/-/raw/master/README.md
2. On Linux, we need to override Firefox’s recognition of mardown files as text files, which is explained in the [Support local files on Linux](https://github.com/KeithLRobertson/markdown-viewer#support-for-local-files-on-linux) section of the README. (I think Option 2. is the most reliable in there.)   
   Firefox does not allow extensions to match mime types, so we can only modify text files which are displayed in the browser − for any other mime type the browser will try to use a default action such as downloading the file. On the web, markdown is served as text so that is not an issue, but local files on Linux get recognized as their specific mime type. Try `xdg-mime query filetype file.md`. The `helpers.private_mime_types_file` allows to override that in Firefox on Linux.

**Comment by erezinman** [comment]
Thank you. I read the README and accidently went straight to the last section about Ubuntu 21+ (I search "ubuntu" in the page) and missed the whole part before it.
